In [1]:
#opening a local csv file
import pandas as pd
df=pd.read_csv("aug_test-selected-columns.csv")

In [2]:
import pandas as pd

# CSV file URL
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

# Read the CSV file
df = pd.read_csv(url)

# Display the first 5 rows
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:

#handling with tsv file
pd.read_csv("movie_titles_metadata.tsv",sep="\t")# no col name

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [4]:
pd.read_csv("movie_titles_metadata.tsv",sep="\t",names=['srno','name','release_year','rating','votes','genres'])#giving col name by using name parameter

,srno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [8]:
df=pd.read_csv("aug_test-selected-columns.csv",index_col='enrollee_id')

In [5]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:
# we alos use header parameter when our col name become 1st row

In [11]:
#use_col parameter 
df

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size
enrollee_id,,,,,,,,,
32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10
9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN
31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN
27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49
27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+
...,...,...,...,...,...,...,...,...,...
1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN
195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN
31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN
7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500
12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+

In [6]:
df.shape

(150, 5)

In [7]:
df=pd.read_csv("aug_test-selected-columns.csv",usecols=['enrollee_id','gender','education_level'])

In [8]:
df

      enrollee_id  gender education_level
0           32403    Male        Graduate
1            9858  Female        Graduate
2           31806    Male     High School
3           27385    Male         Masters
4           27724    Male        Graduate
...           ...     ...             ...
2124         1289    Male        Graduate
2125          195    Male         Masters
2126        31762    Male  Primary School
2127         7873    Male     High School
2128        12215    Male         Masters

[2129 rows x 3 columns]

In [10]:
df = pd.read_csv(
    "aug_test-selected-columns.csv",
    usecols=['enrollee_id']
)

s = df.squeeze("columns")

print(s)

0       32403
1        9858
2       31806
3       27385
4       27724
        ...
2124     1289
2125      195
2126    31762
2127     7873
2128    12215
Name: enrollee_id, Length: 2129, dtype: int64

In [11]:
#skip rows,nrows
df = pd.read_csv(
    "aug_test-selected-columns.csv",
    skiprows=[0,1]
)
df

,9858,city_103,0.92,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,Unnamed: 9
0,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN
1,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49
2,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+
3,217,city_23,0.899,Male,No relevent experience,Part time course,Masters,STEM,10,NaN
4,21465,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,<1,100-500
...,...,...,...,...,...,...,...,...,...,...
2122,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN
2123,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN
2124,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN
2125,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500
2126,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+

In [13]:
df = pd.read_csv(
    "aug_test-selected-columns.csv",
    nrows=100)
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+
...,...,...,...,...,...,...,...,...,...,...
95,2934,city_75,0.939,Male,Has relevent experience,no_enrollment,Phd,STEM,>20,1000-4999
96,12919,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,Humanities,4,NaN
97,4386,city_21,0.624,Male,No relevent experience,Full time course,High School,NaN,3,<10
98,22462,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,9,10000+
99,13988,city_103,0.920,NaN,Has relevent experience,Part time course,Masters,STEM,16,10000+

In [ ]:
#encoding parameter
pd.read_csv("",encoding=""
           )

In [ ]:
#skipbad lines

In [16]:
pd.read_csv("BX-Books.csv",sep=';',encoding='latin-1',on_bad_lines="skip")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11172\795595452.py:1: DtypeWarning: Columns (0: 2002) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("BX-Books.csv",sep=';',encoding='latin-1',on_bad_lines="skip")

,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
1,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
2,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
3,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
4,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
...,...,...,...,...,...,...,...,...
271354,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271355,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271356,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271357,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271358,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [17]:
#dtypes parameter
df = pd.read_csv(
    "aug_test-selected-columns.csv",dtype={'col name': datatype uou want to convert})
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+
...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+

In [19]:
#handling dates
pd.read_csv("IPL Matches 2008-2020.csv",parse_dates=['date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    datetime64[us]
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(13)
memory usage: 225.0 KB

In [20]:
#convertors
def rename(name):
    if name =="Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [21]:
pd.read_csv("IPL Matches 2008-2020.csv",converters={'team1':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [22]:
#na values parameters
pd.read_csv("aug_test-selected-columns.csv",na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size
0,32403,city_41,0.827,NaN,Has relevent experience,Full time course,Graduate,STEM,9,<10
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN
2,31806,city_21,0.624,NaN,No relevent experience,no_enrollment,High School,NaN,<1,NaN
3,27385,city_13,0.827,NaN,Has relevent experience,no_enrollment,Masters,STEM,11,10/49
4,27724,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+
...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,NaN,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN
2125,195,city_136,0.897,NaN,Has relevent experience,no_enrollment,Masters,STEM,18,NaN
2126,31762,city_100,0.887,NaN,No relevent experience,no_enrollment,Primary School,NaN,3,NaN
2127,7873,city_102,0.804,NaN,Has relevent experience,Full time course,High School,NaN,7,100-500
2128,12215,city_102,0.804,NaN,Has relevent experience,no_enrollment,Masters,STEM,15,10000+

In [25]:

#loading huge dataset in chunks

dfs=pd.read_csv("aug_test-selected-columns.csv",chunksize=500)

In [28]:
for chunks in dfs:
    print(chunks.shape)

(500, 10)
(500, 10)
(129, 10)